# Generated by Django 3.2.4 on 2021-06-30 11:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCategorymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='image')),
            ],
            options={
                'verbose_name': 'ərazi',
                'verbose_name_plural': 'ərazilər',
                'db_table': 'ərazi',
            },
        ),
        migrations.CreateModel(
            name='Addermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('specify', models.CharField(choices=[('DAĞLIQ', 'DAĞLIQ'), ('DÜZƏNLİK', 'DÜZƏNLİK'), ('DƏNİZQIRAĞI', 'DƏNİZQIRAĞI'), ('SƏHRA', 'SƏHRA')], default='DAĞLIQ', max_length=20)),
                ('photo', models.ImageField(upload_to='image')),
                ('content', ckeditor.fields.RichTextField()),
                ('wdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazi', to='bloh.areacategorymodel')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yazıs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
