# Generated by Django 3.2.4 on 2021-06-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloh', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addermodel',
            options={'verbose_name': 'Yazı', 'verbose_name_plural': 'Yazılar'},
        ),
        migrations.AddField(
            model_name='addermodel',
            name='population',
            field=models.FloatField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='addermodel',
            table='Yazılanlar',
        ),
    ]
