# Generated by Django 3.2.4 on 2021-06-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloh', '0002_auto_20210630_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentarticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('wdate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Commentlər',
                'db_table': 'Commentlər',
            },
        ),
    ]
